version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r backend/requirements.txt || true
  pre_build:
    commands:
      - echo Logging in to Docker if needed
  build:
    commands:
      - echo Build started on `date`
      - echo Building backend image (example)
      - docker build -t congdon-backend:${CODEBUILD_RESOLVED_SOURCE_VERSION} -f backend/Dockerfile backend || true
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
